AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 1024
    Runtime: dotnet8
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        PRODUCT_TABLE_NAME:
          Ref: Table
        ASPNETCORE_ENVIRONMENT: Development
Resources:
  HeathCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./HealthCheck/
      Handler: HealthCheck::HealthCheck.HealthController::Check
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /health/
            Method: GET
    Metadata:
      SamResourceId: HeathCheckFunction
      
  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Auth/
      Handler: Auth::Auth.AuthController::Register
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /auth/register
            Method: POST
    Metadata:
      SamResourceId: RegisterUserFunction
      
  LoginUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Auth/
      Handler: Auth::Auth.AuthController::Login
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /auth/login
            Method: POST
    Metadata:
      SamResourceId: LoginUserFunction
