version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloakdb -h postgres -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: bitnami/keycloak
    restart: always
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloakdb
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloakpassword
      KEYCLOAK_EXTRA_ARGS: --import-realm
    volumes:
#      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./config/:/opt/bitnami/keycloak/data/import
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

#  kong-database:
#    image: postgres:13
#    container_name: kong-database
#    environment:
#      POSTGRES_DB: kong
#      POSTGRES_USER: kong
#      POSTGRES_PASSWORD: kong
#    ports:
#      - "5433:5432"
#    volumes:
#      - kong_data:/var/lib/postgresql/data
#
#  kong-migration:
#    image: kong:latest
#    container_name: kong-migration
#    environment:
#      KONG_DATABASE: postgres
#      KONG_PG_HOST: kong-database
#      KONG_PG_PASSWORD: kong
#      KONG_CASSANDRA_CONTACT_POINTS: "kong-database"
#    depends_on:
#      - kong-database
#    command: "kong migrations bootstrap"
#
#  kong:
#    image: kong:latest
#    container_name: kong
#    environment:
#      KONG_DATABASE: postgres
#      KONG_PG_HOST: kong-database
#      KONG_PG_PASSWORD: kong
#      KONG_PROXY_ACCESS_LOG: /dev/stdout
#      KONG_ADMIN_ACCESS_LOG: /dev/stdout
#      KONG_PROXY_ERROR_LOG: /dev/stderr
#      KONG_ADMIN_ERROR_LOG: /dev/stderr
#      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
#    ports:
#      - "8000:8000"  # Proxy
#      - "8443:8443"  # Proxy SSL
#      - "8001:8001"  # Admin API
#      - "8444:8444"  # Admin API SSL
#    depends_on:
#      - kong-database
#      - kong-migration
#
#  konga:
#    image: pantsel/konga:latest
#    container_name: konga
#    environment:
#      - NODE_ENV=production
#      - KONGA_CONNECTION_STRING=postgres://kong:kong@kong-database:5432/konga
#    ports:
#      - "1337:1337"
#    depends_on:
#      - kong
#      - kong-database

volumes:
  postgres_data:
  kong_data:
