version: '3.8'

services:
  authentication:
    image: bitnami/keycloak
    restart: always
    container_name: authentication
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: A7wY8jK2
      KEYCLOAK_DATABASE_HOST: keycloakdb.c3y26so8qgto.us-east-2.rds.amazonaws.com
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloakdb
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: A7wY8jK2
      KEYCLOAK_EXTRA_ARGS: --import-realm
    volumes:
      - ./config/:/opt/bitnami/keycloak/data/import
    ports:
      - "8081:8080"
      - "8443:8443"
