version: '3.8'

services:
  authentication:
    build:
      context: ..
      dockerfile: Authentication.Presentation/Dockerfile
    ports:
      - 8081:8083
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8083
